/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.oauth.jsonc --env=preview --include-runtime=false --strict-vars=false --env-interface=OAuthPreviewEnv oauth-worker-configuration.d.ts` (hash: 372061e9c49bd5a346e2c70b28d3360c)
interface __BaseEnv_OAuthPreviewEnv {
	OAUTH_REDIRECT_URI: string;
	DATABASE_URL: string;
	TMDB_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/oauth-preview-worker");
	}
	interface Env extends __BaseEnv_OAuthPreviewEnv {}
}
interface OAuthPreviewEnv extends __BaseEnv_OAuthPreviewEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OAUTH_REDIRECT_URI" | "DATABASE_URL" | "TMDB_API_KEY">> {}
}
