/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.oauth.jsonc --env=preview --include-runtime=false --strict-vars=false --env-interface=OAuthPreviewEnv oauth-worker-configuration.d.ts` (hash: b89e58bef49e3543cb76f1460855c0f2)
interface __BaseEnv_OAuthPreviewEnv {
	OAUTH_REDIRECT_URI: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/oauth-preview-worker");
	}
	interface Env extends __BaseEnv_OAuthPreviewEnv {}
}
interface OAuthPreviewEnv extends __BaseEnv_OAuthPreviewEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OAUTH_REDIRECT_URI">> {}
}
