/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth-client-metadata[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth-client-metadata.json',
    path: '/oauth-client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oauth-client-metadata.json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oauth-client-metadata.json'
  id: '__root__' | '/' | '/oauth-client-metadata.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-client-metadata.json': {
      id: '/oauth-client-metadata.json'
      path: '/oauth-client-metadata.json'
      fullPath: '/oauth-client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
